# Find libunwind
#
#  LIBUNWIND_INCLUDE_DIR - Location of unwind.h, etc
#  LIBUNWIND_LIBRARIES   - List of libraries when using libunwind
#  LIBUNWIND_FOUND       - True if libunwind was found.

# Look for the header file
FIND_PATH(LIBUNWIND_INCLUDE_DIR NAMES unwind.h PATH_SUFFIXES unwind)

# Look for the library
FIND_LIBRARY(LIBUNWIND_LIBRARIES NAMES unwind)

# handle the QUIETLY and REQUIRED arguments and set LIBUNWIND_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBUNWIND DEFAULT_MSG LIBUNWIND_LIBRARIES LIBUNWIND_INCLUDE_DIR)

# Copy the results to the output variables.
IF(LIBUNWIND_FOUND)
  SET(LIBUNWIND_LIBRARIES ${LIBUNWIND_LIBRARY} ${BLAS_LIBRARIES})
  SET(LIBUNWIND_INCLUDE_DIRS ${LIBUNWIND_INCLUDE_DIR})
ELSE(LIBUNWIND_FOUND)
  SET(LIBUNWIND_LIBRARIES)
  SET(LIBUNWIND_INCLUDE_DIRS)
ENDIF(LIBUNWIND_FOUND)

MARK_AS_ADVANCED(LIBUNWIND_INCLUDE_DIRS LIBUNWIND_LIBRARY LIBUNWIND_FOUND)
