# Find Hot Class
#
#  HOTCLASS_INCLUDE_DIR - Location of class.h, etc
#  HOTCLASS_LIBRARIES   - List of libraries when using HOTCLASS
#  HOTCLASS_FOUND       - True if HOTCLASS was found.

# See if we have HOT_CLASS defined
if (NOT HOTCLASS_ROOT AND NOT $ENV{HOT_CLASS} STREQUAL "")
  set(HOTCLASS_ROOT $ENV{HOT_CLASS})
endif()

# Look for the header file
FIND_PATH(HOTCLASS_INCLUDE_DIR NAMES class.h HINTS ${HOTCLASS_ROOT} PATH_SUFFIXES include)

# Look for the library
FIND_LIBRARY(HOTCLASS_LIBRARIES NAMES class HINTS ${HOTCLASS_ROOT})

# handle the QUIETLY and REQUIRED arguments and set HOTCLASS_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(HOTCLASS DEFAULT_MSG HOTCLASS_LIBRARIES HOTCLASS_INCLUDE_DIR)

# Copy the results to the output variables.
IF(HOTCLASS_FOUND)
  SET(HOTCLASS_LIBRARIES ${HOTCLASS_LIBRARY})
  SET(HOTCLASS_INCLUDE_DIRS ${HOTCLASS_INCLUDE_DIR})
ELSE(HOTCLASS_FOUND)
  SET(HOTCLASS_LIBRARIES)
  SET(HOTCLASS_INCLUDE_DIRS)
ENDIF(HOTCLASS_FOUND)

MARK_AS_ADVANCED(HOTCLASS_INCLUDE_DIRS HOTCLASS_LIBRARY HOTCLASS_FOUND)
