TREEHOME=../..
##### Application-specific stuff goes here
treedir=$(TREEHOME)
POSTLIBS=-L$(HOT_CLASS) -lclass_nomp

src=$(prog).c
programname=$(prog)

##### End of application-specific setup

include $(treedir)/Make-common/Make.$(ARCH)

include $(treedir)/Make-common/Make.generic

# DO NOT DELETE THIS LINE -- make depend depends on it.
