# Make.$(ARCH) sets many of the variables used below including:
# CC, CFLAGS, AS, RANLIB, objdir, objsuf, asmdir

treedir=..
treedir_sed=\.\.
appexcludes=
libname=libsw
EXTRACFLAGS=-I$(CLASS)/include

# The "Salmon Warren Utility library"
src:= \
Malloc.c 	key.c \
Msgs.c		error.c 	files.c \
chn.c		dll.c \
stk.c		heap.c		randoms.c \
malloc.c	gc.c		byteswap.c \
timers.c	SDFwrite.c	SDFread.c \
ring.c		qromo.c		qromod.c \
cosmo.c		mpmy_combine.c	counters.c \
mpmy_gather.c	memfile.c 	rsort.c \
msgdirinit.c	singlio.c	abm.c \
mpi_bcast.c	mpi_reduce.c	keycvt.c \
peano.c		SDFreadf.c	hwclock.c \
class_params.c	cosmo_tbl.c
# batch.c		poll.c	\
 
include $(treedir)/Make-common/Make.$(ARCH)

include $(treedir)/Make-common/Make.generic

# DO NOT DELETE THIS LINE -- make depend depends on it.

$(objdir)/Malloc$(objsuf):
$(objdir)/Malloc$(objsuf):
$(objdir)/Malloc$(objsuf):
$(objdir)/Malloc$(objsuf):
$(objdir)/Malloc$(objsuf):
$(objdir)/Malloc$(objsuf):
$(objdir)/Malloc$(objsuf):
$(objdir)/Malloc$(objsuf):
$(objdir)/Malloc$(objsuf):
$(objdir)/Malloc$(objsuf):
$(objdir)/Malloc$(objsuf):
$(objdir)/Malloc$(objsuf): $(treedir)/include/Msgs.h $(treedir)/include/gccextensions.h
$(objdir)/Malloc$(objsuf): $(treedir)/include/Malloc.h $(treedir)/include/error.h $(treedir)/include/malloc.h
$(objdir)/key$(objsuf):
$(objdir)/key$(objsuf):
$(objdir)/key$(objsuf):
$(objdir)/key$(objsuf):
$(objdir)/key$(objsuf):
$(objdir)/key$(objsuf):
$(objdir)/key$(objsuf): $(treedir)/include/key.h
$(objdir)/key$(objsuf):
$(objdir)/key$(objsuf):
$(objdir)/key$(objsuf): $(treedir)/include/protos.h
$(objdir)/Msgs$(objsuf):
$(objdir)/Msgs$(objsuf):
$(objdir)/Msgs$(objsuf):
$(objdir)/Msgs$(objsuf):
$(objdir)/Msgs$(objsuf):
$(objdir)/Msgs$(objsuf):
$(objdir)/Msgs$(objsuf):
$(objdir)/Msgs$(objsuf): $(treedir)/include/mpmy.h
$(objdir)/Msgs$(objsuf): $(treedir)/include/timers.h
$(objdir)/Msgs$(objsuf): $(treedir)/include/Malloc.h
$(objdir)/Msgs$(objsuf): $(treedir)/include/error.h $(treedir)/include/gccextensions.h
$(objdir)/Msgs$(objsuf): $(treedir)/include/Msgs.h $(treedir)/include/protos.h
$(objdir)/error$(objsuf):
$(objdir)/error$(objsuf):
$(objdir)/error$(objsuf):
$(objdir)/error$(objsuf):
$(objdir)/error$(objsuf):
$(objdir)/error$(objsuf):
$(objdir)/error$(objsuf):
$(objdir)/error$(objsuf):
$(objdir)/error$(objsuf):
$(objdir)/error$(objsuf):
$(objdir)/error$(objsuf):
$(objdir)/error$(objsuf):
$(objdir)/error$(objsuf):
$(objdir)/error$(objsuf):
$(objdir)/error$(objsuf):
$(objdir)/error$(objsuf):
$(objdir)/error$(objsuf):
$(objdir)/error$(objsuf):
$(objdir)/error$(objsuf): $(treedir)/include/error.h $(treedir)/include/gccextensions.h
$(objdir)/error$(objsuf): $(treedir)/include/Msgs.h $(treedir)/include/mpmy.h $(treedir)/include/timers.h
$(objdir)/error$(objsuf):
$(objdir)/error$(objsuf): $(treedir)/include/mpmy_abnormal.h $(treedir)/include/protos.h
$(objdir)/error$(objsuf): $(treedir)/include/memfile.h
$(objdir)/files$(objsuf):
$(objdir)/files$(objsuf):
$(objdir)/files$(objsuf):
$(objdir)/files$(objsuf):
$(objdir)/files$(objsuf):
$(objdir)/files$(objsuf):
$(objdir)/files$(objsuf):
$(objdir)/files$(objsuf):
$(objdir)/files$(objsuf):
$(objdir)/files$(objsuf):
$(objdir)/files$(objsuf):
$(objdir)/files$(objsuf):
$(objdir)/files$(objsuf):
$(objdir)/files$(objsuf): $(treedir)/include/protos.h
$(objdir)/files$(objsuf): $(treedir)/include/Malloc.h $(treedir)/include/error.h
$(objdir)/files$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/mpmy.h
$(objdir)/files$(objsuf): $(treedir)/include/timers.h
$(objdir)/files$(objsuf):
$(objdir)/chn$(objsuf): $(treedir)/include/Assert.h $(treedir)/include/error.h
$(objdir)/chn$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/chn.h $(treedir)/include/Msgs.h
$(objdir)/chn$(objsuf): $(treedir)/include/malloc.h
$(objdir)/dll$(objsuf): $(treedir)/include/chn.h $(treedir)/include/dll.h $(treedir)/include/Malloc.h
$(objdir)/dll$(objsuf): $(treedir)/include/error.h $(treedir)/include/gccextensions.h
$(objdir)/stk$(objsuf): $(treedir)/include/Assert.h $(treedir)/include/error.h
$(objdir)/stk$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/stk.h
$(objdir)/stk$(objsuf):
$(objdir)/stk$(objsuf):
$(objdir)/stk$(objsuf):
$(objdir)/stk$(objsuf): $(treedir)/include/Malloc.h
$(objdir)/heap$(objsuf): $(treedir)/include/Assert.h $(treedir)/include/error.h
$(objdir)/heap$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/Malloc.h
$(objdir)/heap$(objsuf): $(treedir)/include/heap.h
$(objdir)/randoms$(objsuf): $(treedir)/include/error.h $(treedir)/include/gccextensions.h
$(objdir)/randoms$(objsuf): $(treedir)/include/randoms.h
$(objdir)/malloc$(objsuf):
$(objdir)/malloc$(objsuf):
$(objdir)/malloc$(objsuf):
$(objdir)/malloc$(objsuf):
$(objdir)/malloc$(objsuf):
$(objdir)/malloc$(objsuf):
$(objdir)/malloc$(objsuf):
$(objdir)/malloc$(objsuf):
$(objdir)/malloc$(objsuf):
$(objdir)/malloc$(objsuf):
$(objdir)/malloc$(objsuf):
$(objdir)/malloc$(objsuf):
$(objdir)/malloc$(objsuf):
$(objdir)/malloc$(objsuf):
$(objdir)/malloc$(objsuf):
$(objdir)/malloc$(objsuf):
$(objdir)/malloc$(objsuf): $(treedir)/include/Msgs.h $(treedir)/include/gccextensions.h
$(objdir)/gc$(objsuf):
$(objdir)/gc$(objsuf):
$(objdir)/gc$(objsuf):
$(objdir)/gc$(objsuf):
$(objdir)/gc$(objsuf):
$(objdir)/gc$(objsuf):
$(objdir)/gc$(objsuf):
$(objdir)/gc$(objsuf):
$(objdir)/gc$(objsuf):
$(objdir)/gc$(objsuf):
$(objdir)/gc$(objsuf):
$(objdir)/gc$(objsuf): $(treedir)/include/gc.h
$(objdir)/byteswap$(objsuf):
$(objdir)/byteswap$(objsuf):
$(objdir)/byteswap$(objsuf):
$(objdir)/byteswap$(objsuf): $(treedir)/include/byteswap.h
$(objdir)/timers$(objsuf):
$(objdir)/timers$(objsuf):
$(objdir)/timers$(objsuf):
$(objdir)/timers$(objsuf): $(treedir)/include/Malloc.h
$(objdir)/timers$(objsuf): $(treedir)/include/error.h $(treedir)/include/gccextensions.h
$(objdir)/timers$(objsuf): $(treedir)/include/timers.h
$(objdir)/timers$(objsuf): $(treedir)/include/mpmy.h
$(objdir)/timers$(objsuf): $(treedir)/include/mpmy_time.h $(treedir)/include/Assert.h
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf): $(treedir)/include/SDF.h $(treedir)/include/SDFwrite.h $(treedir)/include/Malloc.h
$(objdir)/SDFwrite$(objsuf): $(treedir)/include/error.h $(treedir)/include/gccextensions.h
$(objdir)/SDFwrite$(objsuf): $(treedir)/include/mpmy.h $(treedir)/include/timers.h
$(objdir)/SDFwrite$(objsuf):
$(objdir)/SDFwrite$(objsuf): $(treedir)/include/mpmy_io.h $(treedir)/include/Msgs.h $(treedir)/include/protos.h
$(objdir)/SDFwrite$(objsuf): $(treedir)/include/singlio.h
$(objdir)/SDFread$(objsuf):
$(objdir)/SDFread$(objsuf):
$(objdir)/SDFread$(objsuf):
$(objdir)/SDFread$(objsuf):
$(objdir)/SDFread$(objsuf):
$(objdir)/SDFread$(objsuf):
$(objdir)/SDFread$(objsuf):
$(objdir)/SDFread$(objsuf):
$(objdir)/SDFread$(objsuf):
$(objdir)/SDFread$(objsuf):
$(objdir)/SDFread$(objsuf):
$(objdir)/SDFread$(objsuf):
$(objdir)/SDFread$(objsuf):
$(objdir)/SDFread$(objsuf):
$(objdir)/SDFread$(objsuf):
$(objdir)/SDFread$(objsuf):
$(objdir)/SDFread$(objsuf):
$(objdir)/SDFread$(objsuf):
$(objdir)/SDFread$(objsuf):
$(objdir)/SDFread$(objsuf):
$(objdir)/SDFread$(objsuf): $(treedir)/include/mpmy.h $(treedir)/include/timers.h
$(objdir)/SDFread$(objsuf): $(treedir)/include/SDF.h
$(objdir)/SDFread$(objsuf): $(treedir)/include/Assert.h $(treedir)/include/error.h
$(objdir)/SDFread$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/Malloc.h
$(objdir)/SDFread$(objsuf): $(treedir)/include/Msgs.h $(treedir)/include/verify.h $(treedir)/include/SDFread.h
$(objdir)/SDFread$(objsuf): $(treedir)/include/gc.h $(treedir)/include/singlio.h
$(objdir)/ring$(objsuf):
$(objdir)/ring$(objsuf):
$(objdir)/ring$(objsuf):
$(objdir)/ring$(objsuf): $(treedir)/include/ring.h $(treedir)/include/Malloc.h
$(objdir)/ring$(objsuf): $(treedir)/include/error.h $(treedir)/include/gccextensions.h
$(objdir)/ring$(objsuf): $(treedir)/include/mpmy.h $(treedir)/include/timers.h
$(objdir)/ring$(objsuf): $(treedir)/include/gc.h
$(objdir)/ring$(objsuf):
$(objdir)/ring$(objsuf):
$(objdir)/ring$(objsuf):
$(objdir)/ring$(objsuf):
$(objdir)/ring$(objsuf):
$(objdir)/ring$(objsuf):
$(objdir)/ring$(objsuf): $(treedir)/include/Msgs.h
$(objdir)/ring$(objsuf): $(treedir)/include/singlio.h
$(objdir)/qromo$(objsuf):
$(objdir)/qromo$(objsuf):
$(objdir)/qromo$(objsuf):
$(objdir)/qromo$(objsuf):
$(objdir)/qromo$(objsuf):
$(objdir)/qromo$(objsuf):
$(objdir)/qromo$(objsuf): $(treedir)/include/Malloc.h
$(objdir)/qromo$(objsuf): $(treedir)/include/error.h $(treedir)/include/gccextensions.h
$(objdir)/qromo$(objsuf): $(treedir)/include/qromo.h
$(objdir)/qromod$(objsuf):
$(objdir)/qromod$(objsuf):
$(objdir)/qromod$(objsuf):
$(objdir)/qromod$(objsuf):
$(objdir)/qromod$(objsuf):
$(objdir)/qromod$(objsuf):
$(objdir)/qromod$(objsuf): $(treedir)/include/Malloc.h
$(objdir)/qromod$(objsuf): $(treedir)/include/error.h $(treedir)/include/gccextensions.h
$(objdir)/qromod$(objsuf): $(treedir)/include/qromo.h
$(objdir)/cosmo$(objsuf):
$(objdir)/cosmo$(objsuf):
$(objdir)/cosmo$(objsuf):
$(objdir)/cosmo$(objsuf):
$(objdir)/cosmo$(objsuf):
$(objdir)/cosmo$(objsuf):
$(objdir)/cosmo$(objsuf):
$(objdir)/cosmo$(objsuf):
$(objdir)/cosmo$(objsuf):
$(objdir)/cosmo$(objsuf):
$(objdir)/cosmo$(objsuf):
$(objdir)/cosmo$(objsuf):
$(objdir)/cosmo$(objsuf):
$(objdir)/cosmo$(objsuf):
$(objdir)/cosmo$(objsuf):
$(objdir)/cosmo$(objsuf): $(treedir)/include/Msgs.h $(treedir)/include/gccextensions.h
$(objdir)/cosmo$(objsuf): $(treedir)/include/qromo.h $(treedir)/include/cosmo.h
$(objdir)/mpmy_combine$(objsuf):
$(objdir)/mpmy_combine$(objsuf):
$(objdir)/mpmy_combine$(objsuf):
$(objdir)/mpmy_combine$(objsuf):
$(objdir)/mpmy_combine$(objsuf):
$(objdir)/mpmy_combine$(objsuf):
$(objdir)/mpmy_combine$(objsuf):
$(objdir)/mpmy_combine$(objsuf):
$(objdir)/mpmy_combine$(objsuf):
$(objdir)/mpmy_combine$(objsuf): $(treedir)/include/Malloc.h
$(objdir)/mpmy_combine$(objsuf): $(treedir)/include/error.h $(treedir)/include/gccextensions.h
$(objdir)/mpmy_combine$(objsuf): $(treedir)/include/mpmy.h $(treedir)/include/timers.h
$(objdir)/mpmy_combine$(objsuf):
$(objdir)/mpmy_combine$(objsuf): $(treedir)/include/stk.h
$(objdir)/mpmy_combine$(objsuf): $(treedir)/include/gc.h
$(objdir)/mpmy_combine$(objsuf): $(treedir)/include/Msgs.h op_template.c
$(objdir)/counters$(objsuf):
$(objdir)/counters$(objsuf):
$(objdir)/counters$(objsuf):
$(objdir)/counters$(objsuf): $(treedir)/include/Malloc.h
$(objdir)/counters$(objsuf): $(treedir)/include/error.h $(treedir)/include/gccextensions.h
$(objdir)/counters$(objsuf): $(treedir)/include/timers.h
$(objdir)/counters$(objsuf): $(treedir)/include/mpmy.h
$(objdir)/counters$(objsuf): $(treedir)/include/Assert.h
$(objdir)/mpmy_gather$(objsuf):
$(objdir)/mpmy_gather$(objsuf):
$(objdir)/mpmy_gather$(objsuf):
$(objdir)/mpmy_gather$(objsuf):
$(objdir)/mpmy_gather$(objsuf):
$(objdir)/mpmy_gather$(objsuf):
$(objdir)/mpmy_gather$(objsuf):
$(objdir)/mpmy_gather$(objsuf):
$(objdir)/mpmy_gather$(objsuf):
$(objdir)/mpmy_gather$(objsuf):
$(objdir)/mpmy_gather$(objsuf): $(treedir)/include/mpmy.h
$(objdir)/mpmy_gather$(objsuf): $(treedir)/include/timers.h
$(objdir)/mpmy_gather$(objsuf): $(treedir)/include/Msgs.h
$(objdir)/mpmy_gather$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/Malloc.h
$(objdir)/mpmy_gather$(objsuf): $(treedir)/include/error.h $(treedir)/include/gc.h $(treedir)/include/verify.h
$(objdir)/memfile$(objsuf):
$(objdir)/memfile$(objsuf):
$(objdir)/memfile$(objsuf):
$(objdir)/memfile$(objsuf):
$(objdir)/memfile$(objsuf):
$(objdir)/memfile$(objsuf):
$(objdir)/memfile$(objsuf):
$(objdir)/memfile$(objsuf): $(treedir)/include/Malloc.h
$(objdir)/memfile$(objsuf): $(treedir)/include/error.h $(treedir)/include/gccextensions.h
$(objdir)/memfile$(objsuf): $(treedir)/include/Msgs.h $(treedir)/include/protos.h $(treedir)/include/mpmy.h
$(objdir)/memfile$(objsuf): $(treedir)/include/timers.h
$(objdir)/memfile$(objsuf):
$(objdir)/rsort$(objsuf):
$(objdir)/rsort$(objsuf):
$(objdir)/rsort$(objsuf):
$(objdir)/rsort$(objsuf):
$(objdir)/rsort$(objsuf):
$(objdir)/rsort$(objsuf):
$(objdir)/rsort$(objsuf):
$(objdir)/rsort$(objsuf):
$(objdir)/rsort$(objsuf):
$(objdir)/rsort$(objsuf):
$(objdir)/rsort$(objsuf):
$(objdir)/rsort$(objsuf):
$(objdir)/rsort$(objsuf): $(treedir)/include/Malloc.h $(treedir)/include/error.h
$(objdir)/rsort$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/key.h
$(objdir)/rsort$(objsuf):
$(objdir)/rsort$(objsuf):
$(objdir)/rsort$(objsuf):
$(objdir)/msgdirinit$(objsuf):
$(objdir)/msgdirinit$(objsuf):
$(objdir)/msgdirinit$(objsuf):
$(objdir)/msgdirinit$(objsuf):
$(objdir)/msgdirinit$(objsuf):
$(objdir)/msgdirinit$(objsuf):
$(objdir)/msgdirinit$(objsuf):
$(objdir)/msgdirinit$(objsuf):
$(objdir)/msgdirinit$(objsuf):
$(objdir)/msgdirinit$(objsuf):
$(objdir)/msgdirinit$(objsuf):
$(objdir)/msgdirinit$(objsuf):
$(objdir)/msgdirinit$(objsuf):
$(objdir)/msgdirinit$(objsuf):
$(objdir)/msgdirinit$(objsuf):
$(objdir)/msgdirinit$(objsuf):
$(objdir)/msgdirinit$(objsuf):
$(objdir)/msgdirinit$(objsuf):
$(objdir)/msgdirinit$(objsuf):
$(objdir)/msgdirinit$(objsuf):
$(objdir)/msgdirinit$(objsuf):
$(objdir)/msgdirinit$(objsuf): $(treedir)/include/Malloc.h
$(objdir)/msgdirinit$(objsuf): $(treedir)/include/error.h $(treedir)/include/gccextensions.h
$(objdir)/msgdirinit$(objsuf): $(treedir)/include/mpmy_abnormal.h $(treedir)/include/protos.h
$(objdir)/msgdirinit$(objsuf): $(treedir)/include/Msgs.h $(treedir)/include/mpmy.h $(treedir)/include/timers.h
$(objdir)/msgdirinit$(objsuf):
$(objdir)/msgdirinit$(objsuf): $(treedir)/include/files.h $(treedir)/include/mpmy_io.h
$(objdir)/singlio$(objsuf):
$(objdir)/singlio$(objsuf):
$(objdir)/singlio$(objsuf):
$(objdir)/singlio$(objsuf):
$(objdir)/singlio$(objsuf):
$(objdir)/singlio$(objsuf):
$(objdir)/singlio$(objsuf): $(treedir)/include/protos.h
$(objdir)/singlio$(objsuf): $(treedir)/include/mpmy.h $(treedir)/include/timers.h
$(objdir)/singlio$(objsuf): $(treedir)/include/Msgs.h
$(objdir)/singlio$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/singlio.h
$(objdir)/abm$(objsuf):
$(objdir)/abm$(objsuf):
$(objdir)/abm$(objsuf):
$(objdir)/abm$(objsuf):
$(objdir)/abm$(objsuf):
$(objdir)/abm$(objsuf):
$(objdir)/abm$(objsuf):
$(objdir)/abm$(objsuf):
$(objdir)/abm$(objsuf):
$(objdir)/abm$(objsuf):
$(objdir)/abm$(objsuf):
$(objdir)/abm$(objsuf):
$(objdir)/abm$(objsuf):
$(objdir)/abm$(objsuf):
$(objdir)/abm$(objsuf): $(treedir)/include/abm.h
$(objdir)/abm$(objsuf): $(treedir)/include/chn.h $(treedir)/include/dll.h $(treedir)/include/mpmy.h
$(objdir)/abm$(objsuf): $(treedir)/include/timers.h
$(objdir)/abm$(objsuf): $(treedir)/include/protos.h
$(objdir)/abm$(objsuf): $(treedir)/include/Assert.h $(treedir)/include/error.h
$(objdir)/abm$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/Malloc.h
$(objdir)/abm$(objsuf): $(treedir)/include/Msgs.h $(treedir)/include/verify.h $(treedir)/include/gc.h
$(objdir)/mpi_bcast$(objsuf): $(treedir)/include/swampi.h $(treedir)/include/Msgs.h
$(objdir)/mpi_bcast$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/gc.h
$(objdir)/mpi_bcast$(objsuf):
$(objdir)/mpi_bcast$(objsuf):
$(objdir)/mpi_bcast$(objsuf):
$(objdir)/mpi_bcast$(objsuf):
$(objdir)/mpi_bcast$(objsuf):
$(objdir)/mpi_bcast$(objsuf):
$(objdir)/mpi_bcast$(objsuf):
$(objdir)/mpi_bcast$(objsuf):
$(objdir)/mpi_bcast$(objsuf):
$(objdir)/mpi_bcast$(objsuf): $(treedir)/include/error.h
$(objdir)/mpi_reduce$(objsuf):
$(objdir)/mpi_reduce$(objsuf):
$(objdir)/mpi_reduce$(objsuf):
$(objdir)/mpi_reduce$(objsuf):
$(objdir)/mpi_reduce$(objsuf):
$(objdir)/mpi_reduce$(objsuf):
$(objdir)/mpi_reduce$(objsuf):
$(objdir)/mpi_reduce$(objsuf):
$(objdir)/mpi_reduce$(objsuf):
$(objdir)/mpi_reduce$(objsuf):
$(objdir)/mpi_reduce$(objsuf):
$(objdir)/mpi_reduce$(objsuf):
$(objdir)/mpi_reduce$(objsuf): $(treedir)/include/swampi.h $(treedir)/include/stk.h
$(objdir)/mpi_reduce$(objsuf):
$(objdir)/mpi_reduce$(objsuf): $(treedir)/include/Malloc.h $(treedir)/include/error.h
$(objdir)/mpi_reduce$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/gc.h
$(objdir)/mpi_reduce$(objsuf): $(treedir)/include/Msgs.h mpi_template.c
$(objdir)/keycvt$(objsuf): $(treedir)/include/protos.h $(treedir)/include/mpmy.h $(treedir)/include/timers.h
$(objdir)/keycvt$(objsuf):
$(objdir)/keycvt$(objsuf):
$(objdir)/keycvt$(objsuf):
$(objdir)/keycvt$(objsuf): $(treedir)/include/Msgs.h
$(objdir)/keycvt$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/Assert.h
$(objdir)/keycvt$(objsuf): $(treedir)/include/error.h $(treedir)/include/key.h
$(objdir)/keycvt$(objsuf):
$(objdir)/keycvt$(objsuf):
$(objdir)/keycvt$(objsuf): $(treedir)/include/peano.h $(treedir)/include/keycvt.h
$(objdir)/peano$(objsuf): $(treedir)/include/Msgs.h $(treedir)/include/gccextensions.h
$(objdir)/peano$(objsuf): $(treedir)/include/Assert.h $(treedir)/include/error.h $(treedir)/include/key.h
$(objdir)/peano$(objsuf):
$(objdir)/peano$(objsuf):
$(objdir)/peano$(objsuf):
$(objdir)/peano$(objsuf):
$(objdir)/peano$(objsuf):
$(objdir)/peano$(objsuf): $(treedir)/include/vop.h
$(objdir)/SDFreadf$(objsuf):
$(objdir)/SDFreadf$(objsuf):
$(objdir)/SDFreadf$(objsuf):
$(objdir)/SDFreadf$(objsuf):
$(objdir)/SDFreadf$(objsuf):
$(objdir)/SDFreadf$(objsuf):
$(objdir)/SDFreadf$(objsuf):
$(objdir)/SDFreadf$(objsuf):
$(objdir)/SDFreadf$(objsuf):
$(objdir)/SDFreadf$(objsuf):
$(objdir)/SDFreadf$(objsuf):
$(objdir)/SDFreadf$(objsuf):
$(objdir)/SDFreadf$(objsuf):
$(objdir)/SDFreadf$(objsuf):
$(objdir)/SDFreadf$(objsuf):
$(objdir)/SDFreadf$(objsuf):
$(objdir)/SDFreadf$(objsuf):
$(objdir)/SDFreadf$(objsuf):
$(objdir)/SDFreadf$(objsuf):
$(objdir)/SDFreadf$(objsuf):
$(objdir)/SDFreadf$(objsuf): $(treedir)/include/mpmy.h
$(objdir)/SDFreadf$(objsuf): $(treedir)/include/timers.h
$(objdir)/SDFreadf$(objsuf): $(treedir)/include/SDF.h
$(objdir)/SDFreadf$(objsuf): $(treedir)/include/Assert.h $(treedir)/include/error.h
$(objdir)/SDFreadf$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/Malloc.h
$(objdir)/SDFreadf$(objsuf): $(treedir)/include/Msgs.h $(treedir)/include/verify.h $(treedir)/include/SDFread.h
$(objdir)/SDFreadf$(objsuf): $(treedir)/include/gc.h $(treedir)/include/singlio.h
$(objdir)/hwclock$(objsuf):
$(objdir)/hwclock$(objsuf):
$(objdir)/hwclock$(objsuf):
$(objdir)/hwclock$(objsuf):
$(objdir)/hwclock$(objsuf):
$(objdir)/hwclock$(objsuf):
$(objdir)/hwclock$(objsuf):
$(objdir)/hwclock$(objsuf): $(treedir)/include/error.h
$(objdir)/hwclock$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/hwclock.h
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf):
$(objdir)/class_params$(objsuf): $(treedir)/include/cosmo.h $(treedir)/include/Malloc.h
$(objdir)/class_params$(objsuf): $(treedir)/include/error.h $(treedir)/include/gccextensions.h
$(objdir)/cosmo_tbl$(objsuf):
$(objdir)/cosmo_tbl$(objsuf):
$(objdir)/cosmo_tbl$(objsuf):
$(objdir)/cosmo_tbl$(objsuf):
$(objdir)/cosmo_tbl$(objsuf):
$(objdir)/cosmo_tbl$(objsuf):
$(objdir)/cosmo_tbl$(objsuf): $(treedir)/include/cosmo.h
$(objdir)/cosmo_tbl$(objsuf): $(treedir)/include/Malloc.h $(treedir)/include/error.h
$(objdir)/cosmo_tbl$(objsuf): $(treedir)/include/gccextensions.h $(treedir)/include/macr.h
